### ISSUE TITLE
如何添加本地代理

### ISSUE THREAD

**Issue by webnet918** [binyu1231/-obsidian-plugin-proxy#2]
想用v2ray做自定义代理，按照示例都更改为127.0.0.1:portnumber，但是不成功，亲能给个示例吗？

**Comment by ingtshan** [comment]
我的方案是通过[simple\-web\-proxy](https://github.com/ingtshan/simple-web-proxy)进行[网页代理](https://zh.m.wikipedia.org/zh-hans/%E7%BD%91%E9%A1%B5%E4%BB%A3%E7%90%86)
测试可行
![image](https://user-images.githubusercontent.com/81154197/208627345-5039829d-61e3-417e-9ee0-53a40d7b4c71.png)

**Comment by binyu1231** [comment]
新版的obsidian 内部处理了无法访问插件市场的问题，如果你不想更新软件，也可以在 `.obsidian/plugins/obsidian-plugin-proxy/data.json` 这个文件中添加自定义代理。在首页里面README中有示例

**Comment by javalover123** [comment]
> 我的方案是通过[simple-web-proxy](https://github.com/ingtshan/simple-web-proxy)进行[网页代理](https://zh.m.wikipedia.org/zh-hans/%E7%BD%91%E9%A1%B5%E4%BB%A3%E7%90%86) 测试可行 ![image](https://user-images.githubusercontent.com/81154197/208627345-5039829d-61e3-417e-9ee0-53a40d7b4c71.png)

自定义代理的整合解决方案：[https://gitee.com/javalover123/simple-web-proxy](http://link.zhihu.com/?target=https%3A//gitee.com/javalover123/obsidian-plugin-proxy/releases/tag/v0.0.1)
